# frozen_string_literal: true

require 'fileutils'

module Simu
  # Exposes the Simu-managed Android SDK to the user's interactive shell so external
  # toolchains (React Native `npm run android`, Flutter `flutter run`, Gradle) can find
  # ANDROID_HOME, JAVA_HOME, adb, and the emulator. Shell profiles only source a
  # generated env file, so JDK/SDK upgrades never require re-editing the profile.
  module AndroidShellEnv
    BEGIN_MARKER = '# >>> simu android (managed) >>>'
    END_MARKER = '# <<< simu android (managed) <<<'

    module_function

    def env_file
      Simu::AndroidToolchain.managed_env_file
    end

    # Writes the env file and links it from the user's shell profiles.
    # Returns the list of profile paths that were created or changed.
    def apply!(toolchain)
      write_env_file!(toolchain)
      profile_paths.select { |path| link_profile!(path) }
    end

    def write_env_file!(toolchain)
      FileUtils.mkdir_p(File.dirname(env_file))
      File.write(env_file, env_file_contents(toolchain))
    end

    def env_file_contents(toolchain)
      vars, path_entries = toolchain.shell_profile_exports
      lines = ['# Generated by `simu android setup`. Do not edit; re-run setup to refresh.']
      vars.each { |key, value| lines << %(export #{key}="#{value}") }
      joined = (path_entries + ['$PATH']).join(File::PATH_SEPARATOR)
      lines << %(export PATH="#{joined}")
      "#{lines.join("\n")}\n"
    end

    def sourcing_block
      [
        BEGIN_MARKER,
        %([ -f "#{env_file}" ] && . "#{env_file}"),
        END_MARKER
      ].join("\n")
    end

    # ~/.zshrc is the macOS default and is always managed; bash profiles are only
    # touched when they already exist so we don't litter unused files.
    def profile_paths
      home = Dir.home
      paths = [File.join(home, '.zshrc')]
      %w[.bashrc .bash_profile].each do |name|
        candidate = File.join(home, name)
        paths << candidate if File.exist?(candidate)
      end
      paths.uniq
    end

    def link_profile!(path)
      existing = File.exist?(path) ? File.read(path) : ''
      if existing.include?(BEGIN_MARKER) && existing.include?(END_MARKER)
        replace_managed_block(path, existing)
      else
        append_managed_block(path, existing)
      end
    end

    def replace_managed_block(path, existing)
      updated = existing.sub(/#{Regexp.escape(BEGIN_MARKER)}.*?#{Regexp.escape(END_MARKER)}/m, sourcing_block)
      return false if updated == existing

      File.write(path, updated)
      true
    end

    def append_managed_block(path, existing)
      separator = existing.empty? || existing.end_with?("\n") ? '' : "\n"
      File.write(path, "#{existing}#{separator}\n#{sourcing_block}\n")
      true
    end
  end
end
